# PRODUCTION
baseURL = "https://psiconhecer.com/"

# STAGING
# baseURL = "https://psiconhecer.com/psiconhecer2"
# baseURL = "https://192.168.1.7/psiconhecer2"

languageCode = "pr-br"
title = "Psiconhecer"
theme = "bootstrap"
author = "Cesar Barbado"
copyright = "Copyright &copy; Psiconhecer 2021"
disableKinds = ["taxonomy", "term", "section"]
paginate = 24

[[menu.main]]
    name = "Sobre Nós"
    weight = -110
    pre = ""
    url = "#about"

[[menu.main]]
    name = "Publicações"
    weight = -100
    pre = ""
    url = "#public"

[[menu.main]]
    name = "Serviços"
    weight = -90
    pre = ""
    url = "#services"

[[menu.main]]
    name = "Equipe"
    weight = -80
    pre = ""
    url = "#team"

[[menu.main]]
    name = "Contato"
    weight = -70
    pre = ""
    url = "#contact"